#!/usr/bin/python3
# SPDX-FileCopyrightText: 2024 Junsei Iimori <craftboy0228@gmail.com>
# SPDX-License-Identifier: BSD-3-Clause

import sys
import math

def calculate_trig_function(line):
    func, value = line.split()
    value = float(value)  
    
    if func.lower() == "sin":
        return math.sin(math.radians(value))  
    elif func.lower() == "cos":
        return math.cos(math.radians(value))
    elif func.lower() == "tan":
        return math.tan(math.radians(value))

total = 0

for line in sys.stdin:
    line = line.rstrip()  
    if not line:
        continue  
    total += calculate_trig_function(line)

print(f"{total:.2f}")


