#!/usr/bin/python3
#SPDX-FileCopyrightText: 2024 Junsei Iimori <craftboy0228@gmail.com>

import sys

def tonum(s):
    try:
        return int(s)
    except:
        return float(s)

ans = 0

for line in sys.stdin:
    line = line.rstrip()
for line in sys.stdin:
        ans += tonum(line)

print(ans)


