#!/usr/bin/python3
# SPDX-FileCopyrightText: 2024 Junsei Iimori <craftboy0228@gmail.com>
# SPDX-License-Identifier: BSD-3-Clause

import random
import sys

word = open('word.txt', 'r', encoding='UTF-8')

data = word.read().split("\n")
try:
    word_len = int(sys.stdin.readline().strip())
    file_data = [line for line in data if len(line) == word_len]
    if file_data:
        random_word = random.choice(file_data)
        print(random_word)
    else:
        sys.exit("Error: 指定した文字数の単語はない")

except:
    sys.exit("Input Error")


