#!/usr/bin/python3
# SPDX-FileCopyrightText: 2024 Junsei Iimori <craftboy0228@gmail.com>
# SPDX-License-Identifier: BSD-3-Clause

import random
import sys

try:
    with open('word.txt', 'r', encoding='UTF-8') as word:
        data = word.read().split("\n")

    word_len = int(sys.stdin.readline().strip())
    file_data = [line for line in data if len(line) == word_len]
    if file_data:
        random_word = random.choice(file_data)
        print(random_word)
    else:
        print("Error: 指定した文字数の単語はない")
        sys.exit(1)
except ValueError:
    print("Input Error")
    sys.exit(1)

